import os
import json
import shutil
from typing import Dict, Any, List
from loguru import logger

from utils.file_manager import ensure_job_dir, write_json, make_zip

UNITY_STRUCTURE = {
    "sprites": os.path.join("Assets", "Sprites"),
    "textures": os.path.join("Assets", "Textures"),
    "ui": os.path.join("Assets", "UI"),
    "models": os.path.join("Assets", "Models"),
    "audio_music": os.path.join("Assets", "Audio", "Music"),
    "audio_ambient": os.path.join("Assets", "Audio", "Ambient"),
    "audio_sfx": os.path.join("Assets", "Audio", "SFX"),
    "text": os.path.join("Assets", "Text"),
    "metadata": "Metadata",
}

README_CONTENT = """# Unity Import Instructions

This bundle was generated by ABAAD-Agent. To import the assets into Unity:

1. Open or create a Unity project.
2. Copy the `Assets` folder from this bundle into your Unity project's root directory.
   - You can merge with an existing `Assets` folder; Unity will import any new files automatically.
3. Optionally, copy the `Metadata` folder if you want to inspect prompts, theme information, or job metadata.
4. In Unity, allow the editor to re-import assets. Check the Console window for any import warnings.
5. For 3D models (GLB), ensure your Unity version supports GLB import; otherwise, convert to FBX using third-party tools.
6. For audio assets, they are organized into `Assets/Audio/Music` and `Assets/Audio/SFX`.
7. Sprite and texture assets are located in `Assets/Sprites` and `Assets/Textures` respectively.
8. Narrative or dialogue text files can be found under `Assets/Text`.
9. Ambient atmosphere loops are placed in `Assets/Audio/Ambient`.

Tips:
- Assign textures to materials and set the appropriate shader for your render pipeline.
- Adjust audio import settings (compression/looping) in Unity's Inspector as needed.
- Review `Metadata/metadata.json` for the prompts and theme used to generate these assets.

Happy building!
"""


def _ensure_dirs(root: str) -> Dict[str, str]:
    paths = {}
    for key, rel in UNITY_STRUCTURE.items():
        full_path = os.path.join(root, rel)
        os.makedirs(full_path, exist_ok=True)
        paths[key] = full_path
    return paths


def _copy_file(src: str, dst_dir: str) -> str:
    if not src or not os.path.exists(src):
        return ""
    os.makedirs(dst_dir, exist_ok=True)
    dst_path = os.path.join(dst_dir, os.path.basename(src))
    shutil.copy2(src, dst_path)
    return dst_path


def _copy_many(src_list: List[str], dst_dir: str) -> List[str]:
    copied = []
    for item in src_list or []:
        copied_path = _copy_file(item, dst_dir)
        if copied_path:
            copied.append(copied_path)
    return copied


def packaging_node(state: Dict[str, Any]) -> Dict[str, Any]:
    logger.info("packaging_node: assembling Unity-friendly bundle")
    job_dir = ensure_job_dir(state)
    unity_root = os.path.join(job_dir, "UnityBundle")
    unity_paths = _ensure_dirs(unity_root)

    outputs = state.get("outputs", {})
    packaged_index: Dict[str, Any] = {}

    # Visual assets
    sprite_list = outputs.get("sprites")
    if isinstance(sprite_list, list) and sprite_list:
        packaged_index["sprites"] = _copy_many(sprite_list, unity_paths["sprites"])
    else:
        image_path = outputs.get("image_path")
        if image_path:
            packaged_index["sprites"] = [_copy_file(image_path, unity_paths["sprites"])]

    textures = outputs.get("textures")  # future extension
    if isinstance(textures, list):
        packaged_index["textures"] = _copy_many(textures, unity_paths["textures"])

    ui_assets = outputs.get("ui")
    if isinstance(ui_assets, list):
        packaged_index["ui"] = _copy_many(ui_assets, unity_paths["ui"])

    # 3D models
    model_paths = outputs.get("models_3d")
    if isinstance(model_paths, list):
        packaged_index["models"] = _copy_many(model_paths, unity_paths["models"])

    # Audio
    music_list = outputs.get("audio_music")
    if isinstance(music_list, list) and music_list:
        packaged_index["music"] = _copy_many(music_list, unity_paths["audio_music"])
    else:
        audio_path = outputs.get("audio_path")
        if audio_path:
            packaged_index["music"] = [_copy_file(audio_path, unity_paths["audio_music"])]

    ambient_list = outputs.get("audio_ambient")
    if isinstance(ambient_list, list) and ambient_list:
        packaged_index["ambient"] = _copy_many(ambient_list, unity_paths["audio_ambient"])

    sfx_paths = outputs.get("sfx")
    if isinstance(sfx_paths, list):
        packaged_index["sfx"] = _copy_many(sfx_paths, unity_paths["audio_sfx"])

    # Text content
    text_descriptions = outputs.get("text_descriptions")
    if isinstance(text_descriptions, list) and text_descriptions:
        packaged_index["text_descriptions"] = _copy_many(text_descriptions, unity_paths["text"])
    else:
        text_path = outputs.get("text_path")
        if text_path:
            packaged_index["text_descriptions"] = [_copy_file(text_path, unity_paths["text"])]

    dialogue_paths = outputs.get("text_dialogue")
    if isinstance(dialogue_paths, list) and dialogue_paths:
        packaged_index["text_dialogue"] = _copy_many(dialogue_paths, unity_paths["text"])

    lore_paths = outputs.get("text_lore")
    if isinstance(lore_paths, list) and lore_paths:
        packaged_index["text_lore"] = _copy_many(lore_paths, unity_paths["text"])

    # metadata and README
    metadata = {
        "prompt": state.get("prompt"),
        "theme": state.get("theme"),
        "style_guide": state.get("style_guide"),
        "required_assets": state.get("required_assets"),
        "sub_prompts": state.get("sub_prompts"),
        "outputs": outputs,
        "packaged_unity_paths": packaged_index,
        "job_id": state.get("job_id"),
    }

    write_json(unity_paths["metadata"], metadata, filename="metadata.json")

    metadata_state = state.get("metadata")
    if metadata_state:
        write_json(unity_paths["metadata"], metadata_state, filename="node_metadata.json")

    readme_path = os.path.join(unity_root, "README.txt")
    with open(readme_path, "w", encoding="utf-8") as fh:
        fh.write(README_CONTENT)

    zip_path = make_zip(job_dir)
    state["zip_path"] = zip_path
    state.setdefault("packaged", {})["unity_root"] = unity_root
    state["packaged"]["readme"] = readme_path
    state["packaged"]["metadata"] = os.path.join(unity_paths["metadata"], "metadata.json")
    state["packaged"]["index"] = packaged_index
    return state
